In [ ]:
pip install gensim

In [ ]:
import gensim
from gensim.models import word2vec,keyedvectors

In [ ]:
import gensim.downloader as api
wv=api.load('word2vec-google-news-300')
wv['king']

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [ ]:
wv.most_similar('cricket')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [ ]:
wv.similarity('cricket','hockey')

0.45641363

In [ ]:
wv.similarity('cinema','drama')

0.24561657

In [ ]:
vec=wv['king']-wv['man']+wv['woman']
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [ ]:
import pandas as pd
df=pd.read_csv('/content/SMSSpamCollection.txt',delimiter='\t',names=['Label','Message'])
df.head()

Label                                            Message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
import nltk
nltk.download('punkt')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
import nltk
import re
from nltk.stem import WordNetLemmatizer
wnl=WordNetLemmatizer()
corpus=[]
for i in range(len(df)):
  words=re.sub('[^a-zA-z]'," ",df['Message'][i])
  words=nltk.word_tokenize(words)
  words=[ wnl.lemmatize(word)  for word in words ]
  words=" ".join(words)
  corpus.append(words)




In [ ]:
corpus

['Go until jurong point crazy Available only in bugis n great world la e buffet Cine there got amore wat',
 'Ok lar Joking wif u oni',
 'Free entry in a wkly comp to win FA Cup final tkts st May Text FA to to receive entry question std txt rate T C s apply over s',
 'U dun say so early hor U c already then say',
 'Nah I don t think he go to usf he life around here though',
 'FreeMsg Hey there darling it s been week s now and no word back I d like some fun you up for it still Tb ok XxX std chgs to send to rcv',
 'Even my brother is not like to speak with me They treat me like aid patent',
 'As per your request Melle Melle Oru Minnaminunginte Nurungu Vettam ha been set a your callertune for all Callers Press to copy your friend Callertune',
 'WINNER As a valued network customer you have been selected to receivea prize reward To claim call Claim code KL Valid hour only',
 'Had your mobile month or more U R entitled to Update to the latest colour mobile with camera for Free Call The Mobile

**Simple pre process**

In [ ]:
from gensim.utils import simple_preprocess
words=[]
for i in corpus:
  sentences = nltk.sent_tokenize(i)
  for sent in sentences:
    sent= simple_preprocess(sent)
    words.append(sent)
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

# **Building a model from scratch**

In [ ]:
from gensim.models import Word2Vec,keyedvectors

In [ ]:
model=gensim.models.Word2Vec(words)

In [ ]:
model.wv['copy']

array([-0.05052352,  0.05416831,  0.02440261,  0.00141786,  0.03694965,
       -0.16193691,  0.04423234,  0.1914576 , -0.08809379, -0.05583703,
       -0.05167878, -0.15448691, -0.03808574,  0.01124874,  0.01188426,
       -0.05754831,  0.00835926, -0.12191397, -0.01477796, -0.19739322,
        0.06781489,  0.04802414,  0.05165572, -0.0424807 , -0.03559747,
        0.0104253 , -0.08951689, -0.0522702 , -0.04937407,  0.02477051,
        0.1096284 ,  0.00653129,  0.0835572 , -0.09462827, -0.03597774,
        0.11515597, -0.01295952, -0.05624563, -0.02919901, -0.17168875,
        0.05392148, -0.11621535, -0.05474264,  0.01741748,  0.05514621,
        0.00559042, -0.07932369, -0.03044867,  0.08326165,  0.04429746,
        0.09226248, -0.10862417, -0.0261816 , -0.01324942, -0.06416046,
        0.05823642,  0.05826095, -0.00333418, -0.11511521,  0.09093779,
       -0.01108527,  0.04431539,  0.01892661, -0.01298048, -0.12351344,
        0.09103614,  0.06119615,  0.05802964, -0.12526223,  0.08

In [ ]:
## To Get All the Vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'and',
 'in',
 'is',
 'it',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'not',
 'but',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'what',
 'day',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'got',
 'like',
 'time',
 'good',
 'am',
 'then',
 'there',
 'he',
 'text',
 'only',
 'love',
 'want',
 'wa',
 'send',
 'one',
 'need',
 'txt',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'today',
 'lor',
 'sorry',
 'see',
 'still',
 'take',
 'mobile',
 'back',
 'da',
 'dont',
 'reply',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'her',
 'any',
 'ha',
 'did',
 'been',
 'some',
 'msg',
 'an',
 'dear',
 'night',
 'make',
 'here',
 'who',
 'well',
 'say',
 'where',
 'min',
 'message',
 're',
 'much',
 'claim',
 'great',
 'o

In [ ]:
model.corpus_count

5569

In [ ]:

def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)

    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [ ]:
pip install tqdm

In [ ]:
from tqdm import tqdm
import numpy as np
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  7%|▋         | 368/5569 [00:00<00:01, 3667.77it/s]/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.10/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:01<00:00, 3324.78it/s]


In [ ]:
X

[array([-0.12675498,  0.15107758,  0.06162703, -0.02274632,  0.10699151,
        -0.4393252 ,  0.11148539,  0.5376503 , -0.2257829 , -0.16998777,
        -0.14597914, -0.4353491 , -0.12275698,  0.04214354,  0.04883484,
        -0.1797231 ,  0.03968967, -0.2950783 , -0.01865694, -0.55669475,
         0.21474808,  0.13482693,  0.15669276, -0.1289296 , -0.07557167,
         0.0183515 , -0.25357467, -0.15325777, -0.1580264 ,  0.08244025,
         0.3071453 ,  0.0363979 ,  0.2402448 , -0.25316158, -0.09064332,
         0.33145943, -0.06824169, -0.13220666, -0.09909259, -0.47131866,
         0.1400436 , -0.33553854, -0.1642007 ,  0.04580357,  0.17733915,
        -0.01766453, -0.23560025, -0.09599957,  0.25693768,  0.11788823,
         0.28122333, -0.28064278, -0.09748529, -0.0302972 , -0.15037614,
         0.13207778,  0.18123962, -0.02824018, -0.3242016 ,  0.23427178,
        -0.04645698,  0.09656048,  0.04780916, -0.04936508, -0.31730685,
         0.26230606,  0.18579665,  0.17429107, -0.3

In [ ]:
type(X)

list

In [ ]:
X[1]

array([-0.11176735,  0.13791797,  0.05662641, -0.02417616,  0.10271776,
       -0.38688192,  0.09626115,  0.4730758 , -0.19533153, -0.14523628,
       -0.1284502 , -0.37517026, -0.10062255,  0.04430446,  0.04382589,
       -0.16294838,  0.03737916, -0.25865352, -0.03507229, -0.48439798,
        0.18888648,  0.11969403,  0.1319579 , -0.11641963, -0.05646404,
        0.01515675, -0.22322556, -0.14070483, -0.13050961,  0.06954885,
        0.27100587,  0.03481695,  0.1995339 , -0.21399246, -0.09192065,
        0.28812376, -0.05972015, -0.10855972, -0.08364256, -0.41545945,
        0.1188667 , -0.3020951 , -0.13705426,  0.02685576,  0.14993459,
       -0.01704909, -0.21452357, -0.08594286,  0.22736202,  0.10041699,
        0.24456319, -0.24397655, -0.08255146, -0.02301864, -0.13854377,
        0.11325146,  0.16544673, -0.03068378, -0.28728193,  0.20323001,
       -0.02343943,  0.08384738,  0.03528016, -0.04702847, -0.285219  ,
        0.22003368,  0.15656385,  0.14451279, -0.31649244,  0.21

In [ ]:
X[0].shape

(100,)

**train and test shape is different**

after preprocessing 3 rows are removed

In [ ]:
filtered_items = [
    (i, j, k)
    for i, j, k in zip(map(len, corpus), corpus, df['Message'])
    if i < 1
]
filtered_items

[(0, '', '645'), (0, '', ':) '), (0, '', ':-) :-)')]

In [ ]:
y = df[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.get_dummies(y['Label'])
y=y.iloc[:,0].values

In [ ]:
y.shape

(5569,)

In [ ]:
X[0].reshape(1,-1).shape

(1, 100)

In [ ]:
import pandas as pd
import numpy as np

  # Replace with your actual data

# Collect DataFrames in a list
dfs = [pd.DataFrame([x]) for x in X]

# Concatenate all DataFrames into one
new_df = pd.concat(dfs, ignore_index=True)



<ipython-input-31-e3b51ace4a9e>:10: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  new_df = pd.concat(dfs, ignore_index=True)


In [ ]:
print(new_df)

            0         1         2         3         4         5         6   \
0    -0.126755  0.151078  0.061627 -0.022746  0.106992 -0.439325  0.111485   
1    -0.111767  0.137918  0.056626 -0.024176  0.102718 -0.386882  0.096261   
2    -0.135752  0.143532  0.073815  0.007309  0.100134 -0.488579  0.142563   
3    -0.167199  0.211156  0.078926 -0.037310  0.151187 -0.594896  0.149014   
4    -0.147187  0.176547  0.077739 -0.026852  0.134528 -0.510584  0.124721   
...        ...       ...       ...       ...       ...       ...       ...   
5564 -0.152470  0.175176  0.079331 -0.005832  0.126032 -0.550327  0.154431   
5565 -0.157613  0.171243  0.083410 -0.022464  0.133002 -0.546308  0.138400   
5566 -0.178901  0.213729  0.076218 -0.034185  0.142432 -0.596002  0.149420   
5567 -0.160317  0.184104  0.077337 -0.021070  0.129714 -0.544967  0.142847   
5568 -0.164561  0.187774  0.078980 -0.011584  0.128483 -0.578053  0.153789   

            7         8         9   ...        90        91    

In [ ]:
y.shape

(5569,)

In [ ]:
X=new_df

In [ ]:
new_df['Output']=y

In [ ]:
new_df.dropna(inplace=True)

In [ ]:
X=new_df.drop('Output',axis=1)
y=new_df['Output']

In [ ]:
## Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(  )

In [ ]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred=classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.9694244604316546
